### ISSUE TITLE
Cannot specify Ceph Client ID

### ISSUE THREAD

**Issue by olifre** [wamdam/backy2#18]
Hi,

it seems everybody else is just using the `client.admin` key, but I would prefer to use a less privileged key for backup. 
For this, `id` needs to be specified as outlined here:
https://github.com/haiwen/seafile/issues/800#issuecomment-70255802
i.e. something like:
```
ceph_client_id = config.get('ceph_client_id')
self.cluster = rados.Rados(conffile=conf.ceph_conf_file, rados_id=ceph_client_id)
```
should be used here:
https://github.com/wamdam/backy2/blob/eb304fa6663cd19583c9c850015f05602cedb730/src/backy2/io/rbd.py#L31

Would you be willing to add this?

**Comment by mennozon** [comment]
Thanks @olifre, I've justed used this pull request on my backup machine.

Is there anything blocking this from getting merged?

**Comment by doransmestad** [comment]
I just ran into the same issue as we are using a less-privileged user as well. Thanks for the PR @olifre, helped me work through it.   @wamdam  thoughts on merging this in?

**Comment by wamdam** [comment]
Sorry, didn't get previous emails from github regarding this issue.
As far as I can say, the "name" parameter would be also possible as the rados lib creates it from the rados_id parameter:

```python
 341         if rados_id and name:                                                                                                          
 342             raise Error("Rados(): can't supply both rados_id and name")                                                                
 343         elif rados_id:                                                                                                                 
 344             name = 'client.' + rados_id                                                                                                
 345         elif name is None:                                                                                                             
 346             name = 'client.admin'                                                                                                      
```

Also the clustername could be configurable:
```python
 347         if clustername is None:                                                                                                        
 348             clustername = 'ceph'       
```

So I'd say to have these two additions to the config in [io_rbd]:
```
rados_name (default: client.admin)
cluster_name (default: ceph)
```

Does this sound sane?

**Comment by mennozon** [comment]
@wamdam sounds good to me!

**Comment by wamdam** [comment]
Just added a branch / pull request. Test please. If it looks good, I'll merge it into master.
https://github.com/wamdam/backy2/pull/31

**Comment by mennozon** [comment]
Tested and working on my new install as of this week.

**Comment by wamdam** [comment]
Thanks, merged into master.
