### ISSUE TITLE
Backup scheduler for automatic creation and removal of Backy2 backups

### ISSUE THREAD

**Issue by flaviostutz** [wamdam/backy2#23]
We needed to manage the creation and removal of backups, so we created Schelly-Backy2 that is an adapter for Schelly to manage Backy2 backups based on custom retention policies (perform backups every day at 3 a.m and keep 2 daily backups, 3 last weekly backup, 6 monthly backups and so on...)

I read somewhere else that Backy2 was planning to add support for backup scheduling. Maybe this utility can help you:
https://github.com/flaviostutz/schelly-backy2
https://github.com/flaviostutz/schelly

What do you think?

**Comment by wamdam** [comment]
Integrations welcome, however a scheduler won't ever be part of backy for the same reason a scheduler isn't part of rsync. One tool for one job.
However thanks for the work done, maybe we could add solutions like this to the docs.
