### ISSUE TITLE
Differences between backy, backy2 and benji.

### ISSUE THREAD

**Issue by SharpThunder** [wamdam/backy2#29]
Hello!

What are the differences between backy, backy2 and benji?
Which one is more production ready?
As I know backy already have a scheduler, Is there a plan to include a scheduler in backy?
Thanks.

https://bitbucket.org/flyingcircus/backy
https://github.com/elemental-lf/benji

**Comment by wamdam** [comment]
Sorry, this is an issue tracker, not a discussion board. However, we use backy2 in production for years now. A scheduler is not planned in backy2, however we plan to create one eventually as an external program.
