### ISSUE TITLE
How to back up multiple VM diskimages/snapshots from Ceph

### ISSUE THREAD

**Issue by symmcom** [wamdam/backy2#30]
Hello, 
I don't believe this issue has not been thought of, I must be missing something. 
I am trying to test Backy2 to backup disk images stored on Ceph RBD. Here is the scenario:
VM ID #101
Disk images: vm-101-disk-0, vm-101-disk-1
Disk #1 Snapshots: snap-vm-101-0-1, snap-vm-102-0-2, snap-vm-101-0-3
Disk #2 Snapshots: snap-vm-101-1-1, snap-vm-102-1-2, snap-vm-101-1-3

I did a backup using the following :
#backy2 backup rbd://vm-101-disk-0@snap-vm-101-0-1 vm-101-disk-0

Now my question is how do I pull all the disk image/snapshots at the same time? Do I have to back up each snapshot separately for each disk image? How does this work with say 50 VMs with 2 disk images each total of 100 disk images? 

I have a script which auto snapshots all of my VMs daily with auto naming. How do I tell Backy2 to always grab the latest snapshot instead of typing it every time for ALL the disk images?

I hope my question/concern makes sense. Any help would be hugely appreciated!

**Comment by wamdam** [comment]
Backy2 is not able to do this (in purpuse). Just write a script which creates a list of your snapshots to be backed up and call backy2 subsequently on each one.
