### ISSUE TITLE
restore to lvm complains about target size

### ISSUE THREAD

**Issue by roadrunnerjb** [wamdam/backy2#34]
I tried to restore a backup into another lvm block dev. So I created that a little bit larger than the original (9G). When I try to restore backy2 complains about target beeing to small.

I removed the lv and created a smaller on, backy2 is working now but this must be an error ?

root@xen1:/recovery# lvcreate --name tmproot --size 9G vmvg
  Logical volume "tmproot" created.

root@xen1:/recovery# backy2  -c /etc/backy-qnap2.cfg  restore -f 2cdd1778-4d0b-11e9-b1a8-001999e0507d file:///dev/vmvg/tmproot
    INFO: $ /usr/bin/backy2 -c /etc/backy-qnap2.cfg restore -f 2cdd1778-4d0b-11e9-b1a8-001999e0507d file:///dev/vmvg/tmproot
   ERROR: Target size is too small. Has 9663676416b, need 8996782080b.
Error opening restore target.

root@xen1:/recovery# lvremove /dev/vmvg/tmproot
Do you really want to remove active logical volume vmvg/tmproot? [y/n]: y
  Logical volume "tmproot" successfully removed

root@xen1:/recovery# lvcreate --name tmproot --size 8G vmvg
  Logical volume "tmproot" created.

root@xen1:/recovery# backy2  -c /etc/backy-qnap2.cfg  restore -f 2cdd1778-4d0b-11e9-b1a8-001999e0507d file:///dev/vmvg/tmproot
    INFO: $ /usr/bin/backy2 -c /etc/backy-qnap2.cfg restore -f 2cdd1778-4d0b-11e9-b1a8-001999e0507d file:///dev/vmvg/tmproot
    INFO: Restored 1/2124 blocks (0.0%)
    INFO: Restored 12/2124 blocks (0.6%)
...

**Comment by wamdam** [comment]
Yes, indeed forcing into a larger file was obviously untested. Fixed in the latest master.

**Comment by roadrunnerjb** [comment]
wow what a fast solution. thx
