### ISSUE TITLE
Deleting backups fails

### ISSUE THREAD

**Issue by olifre** [wamdam/backy2#35]
After the fix for #26 , I am unable to delete any backups:
```
    INFO: $ /opt/backy2/bin/backy2 -c /etc/backy2.cfg rm 10fde482-68cd-11e9-9990-003048c63494
   ERROR: Unexpected exception
   ERROR: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) deleted_blocks.id may not be NULL [SQL: 'INSERT INTO deleted_blocks (uid, size, delete_candidate, time) VALUES (?, ?, ?, ?)'] [parameters: ('d99229d1b3TCsD3X7i6jp9modTzvNLh8', 4194304, 0, 1557314143)]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: deleted_blocks.id may not be NULL
```

That's with a database using the new schema:
```
# sqlite3 backy.sqlite '.schema deleted_blocks'
CREATE TABLE deleted_blocks (
        id BIGINT NOT NULL, 
        uid VARCHAR(32), 
        size BIGINT, 
        delete_candidate INTEGER NOT NULL, 
        time BIGINT NOT NULL, 
        PRIMARY KEY (id)
);
CREATE INDEX ix_deleted_blocks_uid ON deleted_blocks (uid);
```

Any idea what is going wrong? 
With SQLite3, size of integers should not matter at all IIUC since when storing them the on-disk size is determined for each single row.

**Comment by olifre** [comment]
@wamdam : Maybe this is caused by the `blocks` table still containing `id = Column(Integer, primary_key=True, nullable=False)` instead of also using `BigInteger`?

**Comment by wamdam** [comment]
Sounds more like autoflush is causing this. The algorithm looks which block IDs can be deleted and inserts them into deleted_blocks afair. Seems like it tries to add a NULL value. I have it running on a postgresql mostly and haven't had this problem ever. Would you mind trying an older version?

**Comment by olifre** [comment]
> Would you mind trying an older version?

How old a version would you suggest? 
I went back to a37784fcf5c7a3f69b02130538e125eb9f422ebd as a test and it failed in the same way. 

The following looks interesting:
```
[root@backup db]# sqlite3 backy.sqlite 'select count() from blocks';
9956608
[root@backup db]# sqlite3 backy.sqlite 'select count() from blocks where id=0';
3962
```
Any idea what happened there?
Checking those entries, they don't look "wrong":
```
[root@backup db]# sqlite3 backy.sqlite 'select * from blocks where id=0 LIMIT 10';
68d4390925BbtZKghSAcHMJbQAogw4cF|cac915f8-6887-11e9-bdc2-003048c63494|0|2019-04-27 03:00:05.299757|aab6aae0d604d876e47be8335ee00837ddecc7a74cee870c53a52dce9c8716272a27a38d7d5076ebb4f64f43044551b621cc7f8b7403d25ed4c992d396850635|4194304|1
6421e74b9bccLWDPxyDjWL9eHMgioWCk|d7c0ceea-6887-11e9-90eb-003048c63494|0|2019-04-27 03:00:29.764793|b899668e90c498e121fa640a3a9b8b4b86abc69c7f066a5645ca58d6605384964e06f3b8be21041fd93da7a2ad3aa37ab78903d036f6a281b5c5e76cbfb83da5|4194304|1
d301155cbeaUWjBMBhdbJRGjeDmewfzj|df5849a8-6887-11e9-8fa2-003048c63494|0|2019-04-27 03:00:42.642222|a99c0ad9e0f94df48b6093e0c606e62d668eb7120eaa60ef97bebc125b42395c632ecd0e78d9a82fedd2d12b7d08ca2d201adb09a86176840c95eb598f0c93c3|4194304|1
1d03fda6b6cCXuAcUhhn8nJt8pMQXkWk|e6a0972e-6887-11e9-8486-003048c63494|0|2019-04-27 03:00:54.853369|96810b2ccbe3bddcd09c4ce2985807a24a95e3b563b694fe2df27e19245a603db92fbca52035977e7a7bd698802261520e2b18e5319163ccc12f65e75d04a591|4194304|1
bd68c50a54ZQH6h3GNjmUHx334yaSqmV|ee6c2626-6887-11e9-a1dc-003048c63494|0|2019-04-27 03:01:08.181315|663f4969ceb5b1198b0fdbf3318e87e58d8202177ec55d99f2e95f890c6970261b669145285208f97bed602d26c71ef96d40a0ebd36f9c94d4e0b176f3f5f797|4194304|1
7d8410d158bg7V7uJwuGR8vU4rDVwkvi|f3977d9e-6887-11e9-b6e1-003048c63494|0|2019-04-27 03:01:17.213600|0be8ad755b5e8b70c1b504833e80abf998b426f303099448c1537e8f85840add2a9ef2111a50678d6a87567e30582abb38c3b977bca82fd9eac3ab6929726c14|4194304|1
a466180e46oqVwRpz9AqETaxpZS5pWdf|f9844c32-6887-11e9-ab54-003048c63494|0|2019-04-27 03:01:26.456077|442066a707e0bff3d73214f52afe2beeef681c95ed9efe7a490f0174977bb007913f84359ffabccc9e402f7220e86a523ba32909fe0a897b5e398732ef05348d|4194304|1
ab470b1b55CKB8imH6yHTGGCQBbuP66X|fe692786-6887-11e9-9d91-003048c63494|0|2019-04-27 03:01:35.229192|d7175d0755e8b0b239861265db1c76dd7095e87c3ee9e97f8a2ecebd57f2191325c8c8cd4a1830f185ad00e83bcb44aff454c8f3499cc1fe1ead77d48093942b|4194304|1
5c79e070e5WTmFyw2KsLfiu3xWVwir6E|03693532-6888-11e9-a818-003048c63494|0|2019-04-27 03:01:43.244321|62ceb5b115bed492d5ba5b18376894ef1269e747c65ecf874ebdfaea0f65879a17f500fd08a6f4157a862781464c37323281c830fe03b870e8af776b75c0a708|4194304|1
6adcc04a0bxBWF5VowH3XLHtsKThrnJC|08830c8c-6888-11e9-af1b-003048c63494|0|2019-04-27 03:01:51.743978|99de57ef9d5b0bea573a34b74edcd65a3455d0517b4811254d163f2e2c2d5201476e8c9ca373b2b7c97b777f027fe4c7496caff4fd7f390019eafaff5da4ad6a|4194304|1
```

**Comment by wamdam** [comment]
0 != NULL. I don't think there are such entries, but it might be worth a try:

`select * from blocks where id is null;`

**Comment by olifre** [comment]
@wamdam Luckily, there are no such entries:
```
$ sqlite3 backy.sqlite 'select * from blocks where id is null;'
< no output >
```
Other ideas on what I could check?

**Comment by olifre** [comment]
I've purged the full backup store and database and recreated everything from our RBD snapshots. 
Sadly, the issue persists :sad:.

**Comment by wamdam** [comment]
I remember I had this problem in another project once with sqlite. Maybe you're able to test it with postgresql which is the preferred dbms for backy2?

**Comment by olifre** [comment]
> Maybe you're able to test it with postgresql which is the preferred dbms for backy2?

While there are surely many reasons to use PostgreSQL, it does not fit our backup model, since it introduces another dependency to be backed up. I've never observed such issues with SQLite, but I've also never used SQLite via Python.

**Comment by wamdam** [comment]
Postgresql is not so much of a trouble. Just use backy2 export as this command is for exactly that: Keeping metadata along with the backup.
However, I still think this issue should be fixed. Would it be possible that you send the "defective" sqlite db over? E-Mail or something less public would be ok if you prefer.

**Comment by olifre** [comment]
> Postgresql is not so much of a trouble. Just use backy2 export as this command is for exactly that: Keeping metadata along with the backup.

You are right, of course - but there are still the issues of keeping it updated, configuring it to be safe and well-performing, taking over the data when upgrading the OS etc. 
With SQLite, most of this is solved by just placing the single DB file on another volume which is untouched during upgrades :wink:. 



> Would it be possible that you send the "defective" sqlite db over? E-Mail or something less public would be ok if you prefer.

That's possible. Is the contact address on http://backy2.com/ you personally? Otherwise, feel free to drop me a mail to the mail shown in my GitHub account, and I will just reply to that with a link to download the DB. 
Thanks in advance!

**Comment by wamdam** [comment]
Yes, the e-mail address on backy2.com will reach me.

**Comment by wamdam** [comment]
Alright, let's give this a try. As far as I can say, the <id> column in the deleted_blocks table is not required. This column is auto_incrementish on postgresql so it doesn't hurt. However, the only selection ever on this able is based on the uid column. So id can be dropped.

Here are the steps how you can try this:

1. modify src/backy2/meta_backends/sql.py, line 116 and comment out the <id> column:
  `#id = Column(BigInteger, primary_key=True)`

2. sqlite3 backy.sqlite and perform these commands:
  `alter table deleted_blocks rename to temp_deleted_blocks;`
  `create table deleted_blocks (uid VARCHAR(32), size BIGINT, delete_candidate INTEGER NOT NULL, time BIGINT NOT NULL);`
  `insert into deleted_blocks select uid, size, delete_candidate, time from temp_deleted_blocks;`
  (This is the way sqlite performs a drop column action).

After this, backy rm should work. If this works for you, I'll drop the id column for future versions.
In case you're not able to perform step (1), it should also work without this, as <id> is not touched. But I've not tested this.

**Comment by olifre** [comment]
Thanks for investigating! 

> However, the only selection ever on this able is based on the uid column. So id can be dropped.

As you wrote, selection is done on the `uid` column, so I ran the following SQL commands in addition:
```
drop index ix_deleted_blocks_uid
CREATE INDEX ix_deleted_blocks_uid on deleted_blocks (uid);
drop table temp_deleted_blocks;
```
But of course, that would happen automatically when starting with a fresh DB (after committing the change). 

Since we have a second backup (and many snapshots), I patched this (both 1 and 2) into our main backy2 backup store just now and we'll see what happens over night  - it is expendable :wink: .

**Comment by olifre** [comment]
@wamdam That sadly failed miserably - or should only `rm` work? 
Even a simple `ls` seems broken, which our script uses to find versions it might delete:
```
sqlalchemy.exc.ArgumentError: Mapper Mapper|DeletedBlock|deleted_blocks could not assemble any primary key columns for mapped table 'deleted_blocks'
```
Is `uid` useable as a primary key, or may the same `uid` enter the table more than once? 
Also, this part still references the `id`:
https://github.com/wamdam/backy2/blob/da9eda5bf260a3798220facd0b325280e054f4c0/src/backy2/meta_backends/sql.py#L123-L125

**Comment by olifre** [comment]
I checked and it seems sqlalchemy can not handle tables without primary key:
https://stackoverflow.com/questions/34283259/how-to-define-a-table-without-primary-key-with-sqlalchemy
So it seems we have to find a unique column?

**Comment by wamdam** [comment]
Yeah, maybe allowing sqlite in the first place was stupid. This dbms is just not right to hold important and large data. It just made smoke testing a lot simpler.
I think I'd need to look into this for some time. However that's low priority for me as we and others are using postgresql without issues. So does anyone else want to give it a shot?

**Comment by wamdam** [comment]
Alright, I'll let this issue be a sponsoring issue.

**Comment by olifre** [comment]
@wamdam Thanks! We ourselves can not really sponsor (as non-profit education organization, there is no workflow to sponsor software development), but maybe somebody else will also need this feature. 
Would you also be fine with adding the `help wanted` label to ideally attract somebody interested in contributing a fix?

**Comment by wamdam** [comment]
Found the issue. https://docs.sqlalchemy.org/en/13/dialects/sqlite.html
"SQLite’s typing model is based on naming conventions. Among other things, this means that any type name which contains the substring "INT" will be determined to be of “integer affinity”. A type named "BIGINT", "SPECIAL_INT" or even "XYZINTQPR", will be considered by SQLite to be of “integer” affinity. However, the SQLite autoincrement feature, whether implicitly or explicitly enabled, requires that the name of the column’s type is exactly the string “INTEGER”. Therefore, if an application uses a type like BigInteger for a primary key, on SQLite this type will need to be rendered as the name "INTEGER" when emitting the initial CREATE TABLE statement in order for the autoincrement behavior to be available."

It was actually introduced when changing the deletedblocks from id integer to id biginteger due to integer limitations.
I think this is a sqlite annoyance, however it's simple to fix it. Patch will be added in a few minutes.

**Comment by JamshaidF** [comment]
Same issue happened to me with postgress

```
 ERROR: [backy2.logging] (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.DataError) integer out of range
 [SQL: 'INSERT INTO deleted_blocks (uid, size, delete_candidate, time) VALUES (%(uid)s, %(size)s, %(delete_candidate)s, %(time)s) RETURNING deleted_blocks.id'] [parameters: {'uid': 'eda70dd4dbYbaiFCWkjKetkV8H8nDhJG', 'size': 4194304, 'delete_candidate': 0, 'time': 1622493974}] (Background on this error at: http://sqlalche.me/e/9h9h)
```

workaround was to reset the id 

`ALTER SEQUENCE deleted_blocks_id_seq RESTART WITH 1;`

and now i can delete backups again.
it is better to change id field to BigInt

**Comment by wamdam** [comment]
That's probably a very old database. The model changed to bigint quite a while ago:

```
126 class DeletedBlock(Base):
127     __tablename__ = 'deleted_blocks'
128     id = Column(BigInteger().with_variant(Integer, "sqlite"), primary_key=True)
```
