### ISSUE TITLE
CockroachDB metadata backend

### ISSUE THREAD

**Issue by Kanshiroron** [wamdam/backy2#37]
Hello,

I'm trying to use Backy2 with [CockroadDB](https://www.cockroachlabs.com/). Cockroachdb is supposedly fully compatible with PostgreSQL syntax. However, I have an issue when trying to initialize the database (`backy2 initdb`) as it fails to check the database version.

```
    INFO: $ /usr/bin/backy2 initdb
   ERROR: Unexpected exception
   ERROR: Could not determine version from string 'CockroachDB CCL v19.1.2 (x86_64-unknown-linux-gnu, built 2019/06/07 17:32:15, go1.11.6)'
```

Any chance to see Backy2 compatibility with CockroachDB implemented at some point?

Thanks!

**Comment by Kanshiroron** [comment]
I dug a little about this issue, and I found that you are using SQLAlchemy to connect to the SQL database. SQLAchemy is supposed to be compatible with CockroachDB, however the version you are using might be too old since I'm having the error:
`sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:cockroachdb`

Also, if you look at CockroachDB documentation, some options also need to be added for client authentication with TLS certificates.
https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-sqlalchemy.html#step-4-run-the-python-code

**Comment by Kanshiroron** [comment]
I finally was able to make the `backy2 initdb` to function, I had to upgrade the SQLAlchemy wheel, and also install the cockroach wheel. Here is my Dockerfile:

```
FROM ubuntu:xenial

ENV BACKY2_VERSION 2.9.17

# installing backy2
RUN apt-get update -y && \
	apt-get dist-upgrade -y && \
	apt-get install -y wget inotify-tools ceph-common && \
	wget https://github.com/wamdam/backy2/releases/download/v${BACKY2_VERSION}/backy2_${BACKY2_VERSION}_all.deb && \
	apt install -y ./backy2_${BACKY2_VERSION}_all.deb && \
	rm backy2_${BACKY2_VERSION}_all.deb /etc/backy.cfg && \
	apt-get remove --purge -y wget && \
	apt-get autoremove -y && \
	rm -rf /var/lib/apt/lists/*

# upgrading pip wheels
RUN apt-get update -y && \
	apt-get install -y python3-pip && \
	pip3 install pip --upgrade && \
	pip install cockroachdb && \
	pip install SQLAlchemy --upgrade && \
	apt-get remove --purge -y python3-pip && \
	apt-get autoremove -y && \
	rm -rf /var/lib/apt/lists/*

# entrypoint
COPY bootstrap.sh /
RUN chmod 755 /bootstrap.sh && \
	chown root:root /bootstrap.sh
CMD ["/bootstrap.sh"]
```
Is it possible for you to re-generate the package to upgrade SQLAlchemy and include cockroachdb?
Thanks!

**Comment by wamdam** [comment]
no reply
