### ISSUE TITLE
backy2 uses huge amount of RAM backing up RBD objects

### ISSUE THREAD

**Issue by flashydave** [wamdam/backy2#39]
RAM appears to grow linearly as backup proceeds and tracks the size of the object being backed up. Eg 100GB backup using backup.sh will require 100GB RAM or the process will get killed by OOM.
This is on ubuntu 18.04.1 server + backy2_2.9.18 (Earlier versions of OS and backy2 show same symptoms)

**Comment by wamdam** [comment]
What is backup.sh?
backy2 uses about the same amount of RAM no matter how big the backup/restore is. Could you elaborate how you measure this and maybe also provide a process list?

**Comment by flashydave** [comment]
backup.sh was a simple script to iterate over volumes needing backing
up.  I dont have access to the system this was measured on but the
processes using up all the ram was backy2 itself.

As the backup ran the memory increased in line with the amount of data
backed up linearly and then when the backup complete it dropped back to
zero (assuming the system hadnt OOM'ed before then). 

backy2 was running under vmware on ubuntu 18.04 LTS

Dave

**Comment by wamdam** [comment]
Well, backy2 doesn't need a lot of ram, especially not in the gigabytes. In order to not fill the caches/buffers of the OS with backup-data, it has also a protection for that. RAM usage was always a design goal.
In order to see what's wrong, I'll need a full processlist, also all RAM parameters (total, used, buffers/caches, ...).
Without that data I can't even start to look at something, so I'll close this ticket for now.

**Comment by flashydave** [comment]
On 01:48, Sat 05 Oct 19, Daniel Kraft wrote:
> Well, backy2 doesn't need a lot of ram, especially not in the gigabytes. In order to not fill the caches/buffers of the OS with backup-data, it has also a protection for that. RAM usage was always a design goal.
> In order to see what's wrong, I'll need a full processlist, also all RAM parameters (total, used, buffers/caches, ...).
> Without that data I can't even start to look at something, so I'll close this ticket for now.

ok thats your choice.  I understand the difficulties in debuggibg.

Unfortunately I no longer work for the company
where I was running the systems but it was totally reproducable on both
production and staging systems running different ceph versions. The backy2 client weterunning on a
separate machine from the ceph/rbd monitor/managers (which were part of
a kolla openstack deployment.

Dave  B.Sc (Hons) C.Eng MIET
Chartered Engineer
Advisory Systems Architect.
