### ISSUE TITLE
ERROR: No option 'cluster_name' in section: 'io_rbd'

### ISSUE THREAD

**Issue by wech71** [wamdam/backy2#40]
Commit 4fcc7d26c09e4b87d6a2295725e32e825f7cf2ff introduced config options to set cluster_name and rados_name.

Unfortunately this breaks existing configurations and is not yet documented in the config file documentation either.

I suggest do change 
```
        cluster_name = config.get('cluster_name')
        rados_name = config.get('rados_name')
```
to:

```
        cluster_name = config.get('cluster_name', 'ceph')
        rados_name = config.get('rados_name', 'client.admin')

```

to allow omitting the values from the backy2.conf file like probably intended.

**Comment by wamdam** [comment]
Very good, thank you. I've added the recommended defaults.
Actually the change was in the docs, unfortunately, the docs were not synced to the homepage. I've done this now.
