### ISSUE TITLE
Automation script needs adjustment

### ISSUE THREAD

**Issue by ednt** [wamdam/backy2#45]
To make it work we had to replace the followng line
`BACKY_SNAP_VERSION_UID=$(backy2 -m ls -s "$LAST_RBD_SNAP" "$VM"|grep -e '^version'|awk -F '|' '{ print $7 }')`
With
`BACKY_SNAP_VERSION_UID=$(backy2 -m ls -s "$LAST_RBD_SNAP" "$VM"|awk -F '|' 'NR>1 { print $6 }')`

**Comment by wamdam** [comment]
Thanks, fixed. http://backy2.com/docs/backup.html#automation
