### ISSUE TITLE
python libraries have too new versions

### ISSUE THREAD

**Issue by ericfri** [wamdam/backy2#5]
Hey there,
This looks like a nice piece of software, but I can't test it with my Proxmox system, as the required version of setproctitle is to new. Proxmox has version 1.1.8-1, so I tried to install the newest version, 1.1.10-1, but it requires a newer version of Python than is installed, and that just seems to risky to install without a lot of testing.
So basically I was wondering if the version of setproctitle could be dropped back, or is there some compelling reason to keep it at 1.1.10-1?

Thanks

**Comment by wamdam** [comment]
There is no reason for this version, it's just the only one I have tested. I have just confirmed that 1.1.8 works too, so I've changed it in setup.py.
Aren't you using a virtualenv? Because then there'd be no reason to use the old lib.

**Comment by ericfri** [comment]
Thanks,
I was just following the build instructions for the Debian version. I cloned the repo, did make clean, and make deb. Then installed the deb file. Then when I tried "backy2 backup -info" I got the error about setproctitle.

So I guess the answer is no, I'm not using a virtualenv.

**Comment by wamdam** [comment]
So does it work now? Or should I reopen the issue?

**Comment by ericfri** [comment]
It seems that fixed it, but now python3-psutil is too old.

**Comment by wamdam** [comment]
Ok, I'm testing with ubuntu 16.10 here. What's your version?

**Comment by ericfri** [comment]
I'm using the latest Proxmox, which is based on Debian Jessie I believe

**Comment by wamdam** [comment]
Ok, what version of python3-psutil is available there? Maybe that's enough for backy too.
Could you please paste the full error message and your command?

**Comment by ericfri** [comment]
python3-psutil is version 2.1.1-1
The error is: 

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (psutil 2.1.1 (/usr/lib/python3/dist-packages), Requirement.parse('psutil>=2.2.1'))

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/usr/bin/backy2", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil>=2.2.1

**Comment by wamdam** [comment]
Ah, that's interesting. As far as I can see, all you have to do is to modify setup.py to reflect the version that is available for you and test the build.
If you could provide the setup.py when it works I'll see if we can use it generically.

**Comment by ericfri** [comment]
Ok, I changed:
psutil = 2.1.1
sqlalchemy = 0.9.8

Now it seems to work. I will try it more and report back what I find.

**Comment by wamdam** [comment]
Closed as of inactivity.
