### ISSUE TITLE
A way to switch from sqlite to postgresql

### ISSUE THREAD

**Issue by ednt** [wamdam/backy2#53]
Hi,

I had the problem to import an already in use sqlite database to postgresql.
Here is a small HowTo:

1. Install sqlite3 if not already installed.
2. Create a file called export_backy2_sqlite
3. Fill it with:

.output backy2.sql
.mode insert versions
select * from versions;
.mode insert stats
select * from stats;
.mode insert tags
select * from tags;
.mode insert blocks
select * from blocks;
.mode insert deleted_blocks
select * from deleted_blocks;
.quit

4. In the directory of the sqlite database (/var/lib/backy2)
execute:

sqlite3 backy.sqlite -init export_backy2_sqlite

You have to exit sqlite3 by hand, since the .quit or .exit at the end of the file is ignored.

5. Install joe (an editor which can handle very large files)
6. Open the created file with

joe backy2.sql

At the beginning of the file enter a new line with

BEGIN;

as content.

Press CTRL+k v to jump to the end of the file and enter

COMMIT;

Save the file with CTRL+k x

Without this, the import takes ages.

7. Install postgresql if not already done.
8. Run psql and execute:

create user backy2 with encrypted password 'backy2';
create database backy2;
grant all privileges on database backy2 to backy2;

\q

9. Adjust your settings in /etc/backy.cfg or create a new file with postgres settings.
10. Run 

backy2 [c /etc/YourNewFile] initdb

11. Run

psql -q backy2 < /var/lib/backy2/backy2.sql

And wait .....

That's it.

Now you have your sqlite data imported in postgresql.

I hope this saves someone a long time of try and error.

**Comment by ednt** [comment]
Ok,

maybe export/import would be easier ;)

**Comment by JohnDepon** [comment]
I migrated from sqlite3 to postgresql using pgloader.
https://github.com/dimitri/pgloader
It worked without any problems and handled everything automatically.
It is as simple as `pgloader /var/lib.backy2/backy.sqlite postgresql://user:pass@host:5432/backy`

**Comment by JohnDepon** [comment]
A followup on this.
It turns out that the `deleted_blocks` table was not created properly.
The `id` column was not auto incrementing.
As a result the backy2 cleanup command failed.

To fix this I had to create a new sequence in postgresql and then apply it to the id column as the default value.

**Comment by wamdam** [comment]
Just as a note: My recommended way to migrate would be to just export all versions and re-import them. You will of course lose statistics, but that's all.
Hint: Maybe call a 'cleanup -f' after migration because also the deleted_blocks table will be empty and this will cleanup for a fresh start.
