### ISSUE TITLE
Documentation script issue

### ISSUE THREAD

**Issue by rbrayner** [wamdam/backy2#54]
Hi everyone!

I think there is an issue with the script found in the backup section of the docs (http://backy2.com/docs/backup.html). The following line:

BACKY_SNAP_VERSION_UID=$(backy2 -m ls -s "$LAST_RBD_SNAP" "$VM"|awk -F '|' '{ print $6 }')

should be changed to:

BACKY_SNAP_VERSION_UID=$(backy2 -ms ls -s "$LAST_RBD_SNAP" "$VM"|awk -F '|' '{ print $6 }')

The difference is the -ms only. The output was incorrect, since it was returning the string "uid" in addition to the actual UID version. The initial backup then worked as expected, but not the differential_backup function.

Best regards,

Rodrigo Brayner

**Comment by wamdam** [comment]
ack
