### ISSUE TITLE
After deletion, incorrect information is displayed.

### ISSUE THREAD

**Issue by noeyhuy** [wamdam/backy2#57]
**1) backupdata before deletion**
[root@localhost ~]# backy2 stats
    INFO: $ /usr/local/bin/backy2 stats
+---------------------+--------------------------------------+------+------------+-------------+------------+-------------+---------------+----------------+-------------+--------------+--------------+---------------+--------------+
|         date        |                 uid                  | name | size bytes | size blocks | bytes read | blocks read | bytes written | blocks written | bytes dedup | blocks dedup | bytes sparse | blocks sparse | duration (s) |
+---------------------+--------------------------------------+------+------------+-------------+------------+-------------+---------------+----------------+-------------+--------------+--------------+---------------+--------------+
| 2020-03-17 07:15:08 | fc35739c-681e-11ea-a6f1-90b11c43e4ce | test | 2662662144 |         635 | 2662662144 |         635 |    2662662144 |            635 |           0 |            0 |            0 |             0 |           20 |
+---------------------+--------------------------------------+------+------------+-------------+------------+-------------+---------------+----------------+-------------+--------------+--------------+---------------+--------------+
    INFO: Backy complete.

**2) rm -> cleanup sucess**
[root@localhost ~]# backy2 rm fc35739c-681e-11ea-a6f1-90b11c43e4ce -f
    INFO: $ /usr/local/bin/backy2 rm fc35739c-681e-11ea-a6f1-90b11c43e4ce -f
    INFO: Removed backup version fc35739c-681e-11ea-a6f1-90b11c43e4ce with 635 blocks.
    INFO: Backy complete.
         
[root@localhost ~]# backy2 cleanup --full
    INFO: $ /usr/local/bin/backy2 cleanup --full
    INFO: Cleanup: Removed 635 blobs
    INFO: Backy complete.

**3) Why is it displayed in stats after deletion? help.** 
[root@localhost ~]# backy2 stats
    INFO: $ /usr/local/bin/backy2 stats
+---------------------+--------------------------------------+------+------------+-------------+------------+-------------+---------------+----------------+-------------+--------------+--------------+---------------+--------------+
|         date        |                 uid                  | name | size bytes | size blocks | bytes read | blocks read | bytes written | blocks written | bytes dedup | blocks dedup | bytes sparse | blocks sparse | duration (s) |
+---------------------+--------------------------------------+------+------------+-------------+------------+-------------+---------------+----------------+-------------+--------------+--------------+---------------+--------------+
| 2020-03-17 07:15:08 | fc35739c-681e-11ea-a6f1-90b11c43e4ce | test | 2662662144 |         635 | 2662662144 |         635 |    2662662144 |            635 |           0 |            0 |            0 |             0 |           20 |
+---------------------+--------------------------------------+------+------------+-------------+------------+-------------+---------------+----------------+-------------+--------------+--------------+---------------+--------------+
    INFO: Backy complete.
 
**4) I can delete it directly from sqlite**
[root@localhost ~]# sqlite3 /disk/home/backy2/backy.sqlite
sqlite> select * from stats;
date|version_uid|version_name|version_size_bytes|version_size_blocks|bytes_read|blocks_read|bytes_written|blocks_written|bytes_found_dedup|blocks_found_dedup|bytes_sparse|blocks_sparse|duration_seconds
2020-03-17 07:15:08|fc35739c-681e-11ea-a6f1-90b11c43e4ce|test|2662662144|635|2662662144|635|2662662144|635|0|0|0|0|20
 
sqlite> delete from stats where version_uid = 'fc35739c-681e-11ea-a6f1-90b11c43e4ce';

**5) but .. It is very inconvenient to delete manually**

**Comment by wamdam** [comment]
stats is like a log and will stay forever.
`backy2 ls` is where the removed version is not shown again. This is by design. `backy2 stats` should always tell me how long a backup took yesterday/last week/a year ago.
