### ISSUE TITLE
Why is the backup time different?

### ISSUE THREAD

**Issue by noeyhuy** [wamdam/backy2#59]
i need change to KST time.

[root@localhost ~]# backy2 -c /disk/home/backup/backy.cfg ls
    INFO: $ /usr/local/bin/backy2 -c /disk/home/backup/backy.cfg ls
+---------------------+-------------+---------------+-------+--------------+--------------------------------------+-------+-----------+----------------------------+---------------------+
|         **date**        | name        | snapshot_name |  size |   size_bytes |                 uid                  | valid | protected | tags                       |        expire       |
+---------------------+-------------+---------------+-------+--------------+--------------------------------------+-------+-----------+----------------------------+---------------------+
| **2020-03-26 05:37:29** | full_monday |               | 25600 | 107374182400 | e1edf5ac-6f23-11ea-9b11-901b0e6098d7 |   1   |     0     | b_daily,b_monthly,b_weekly | 2020-03-26 14:40:00 |
+---------------------+-------------+---------------+-------+--------------+--------------------------------------+-------+-----------+----------------------------+---------------------+
    INFO: Backy complete.
    
[root@localhost ~]# date
Thu **Mar 26 15:11:34** KST 2020

**Comment by wamdam** [comment]
I recently chose to use UTC as the only time format. We are backing up servers around the world and it's insane to have multiple time zones in the "same" logs. Also, wen using the expire-feature, it's imho easier that way.
However that might change when you have a good reason. Let me know..
