### ISSUE TITLE
Where is the data stored (Ceph RBD)

### ISSUE THREAD

**Issue by bkmz12332** [wamdam/backy2#65]
Where is the data stored after the command?

backy2 backup rbd://test/rbd-6 rbd-6

The path for data storage is specified in the file /etc/backy.cfg
I backup 12 GB, but not on one disk the data volume did not increase

**Comment by wamdam** [comment]
The path is specified in backy.cfg. See http://backy2.com/docs/configuration.html#backy-cfg and search for data_backends
