### ISSUE TITLE
[FEATURE] Automatically export-and-upload metadata after a run

### ISSUE THREAD

**Issue by rjhenry** [wamdam/backy2#68]
Hi,

Many thanks for an excellent project! As you recommend [here](http://backy2.com/docs/administration.html#backy2-export):
> After each backup you should export the generated version and store it together with your backup data (that is in the same backup storage like NFS, S3, …).

It would be nice if it were possible to automate this process in some way, perhaps `backy2 backup --with-export` or similar. This way, metadata is also held with data backups with no further intervention from the administrator.

Many thanks!

**Comment by wamdam** [comment]
Acutally no. First, exports are optional. Another option would be to just dump the database or mirror it.
Second, I don't want my exports to be on the same s3 bucket as my blocks. I'd never find them again.

It's easily scriptable, so I'll leave it to the implementation.
