### ISSUE TITLE
how to using scrub?

### ISSUE THREAD

**Issue by noeyhuy** [wamdam/backy2#69]
# scrub
[root@localhost ~]# backy2 -c backy.cfg ls
    INFO: $ /usr/local/bin/backy2 -c backy.cfg ls
+---------------------+-------------+---------------+-------+--------------+--------------------------------------+-------+-----------+----------------------------+---------------------+
|         date        | name        | snapshot_name |  size |   size_bytes |                 uid                  | valid | protected | tags                       |        expire       |
+---------------------+-------------+---------------+-------+--------------+--------------------------------------+-------+-----------+----------------------------+---------------------+
| 2020-05-25 06:03:21 | full_Monday |               | 25600 | 107374182400 | 6ffdedc2-9e4d-11ea-b3f1-901b0e6098d7 |   1   |     0     | b_daily,b_monthly,b_weekly | 2020-06-01 00:00:00 |
+---------------------+-------------+---------------+-------+--------------+--------------------------------------+-------+-----------+----------------------------+---------------------+
    INFO: Backy complete.

[root@localhost ~]# backy2 scrub 6ffdedc2-9e4d-11ea-b3f1-901b0e6098d7
    INFO: $ /usr/local/bin/backy2 scrub 6ffdedc2-9e4d-11ea-b3f1-901b0e6098d7
    INFO: Backy complete.

# has not changed
[root@localhost ~]# backy2 ls                                        
    INFO: $ /usr/local/bin/backy2 ls
+---------------------+-------------+---------------+-------+--------------+--------------------------------------+-------+-----------+----------------------------+---------------------+
|         date        | name        | snapshot_name |  size |   size_bytes |                 uid                  | valid | protected | tags                       |        expire       |
+---------------------+-------------+---------------+-------+--------------+--------------------------------------+-------+-----------+----------------------------+---------------------+
| 2020-05-25 06:03:21 | full_Monday |               | 25600 | 107374182400 | 6ffdedc2-9e4d-11ea-b3f1-901b0e6098d7 |   1   |     0     | b_daily,b_monthly,b_weekly | 2020-06-01 00:00:00 |
+---------------------+-------------+---------------+-------+--------------+--------------------------------------+-------+-----------+----------------------------+---------------------+
    INFO: Backy complete.

[root@localhost ~]# backy2 -c backy.cfg stats
    INFO: $ /usr/local/bin/backy2 -c backy.cfg stats
+---------------------+--------------------------------------+-------------+--------------+-------------+--------------+-------------+---------------+----------------+-------------+--------------+--------------+---------------+--------------+
|         date        |                 uid                  | name        |   size bytes | size blocks |   bytes read | blocks read | bytes written | blocks written | bytes dedup | blocks dedup | bytes sparse | blocks sparse | duration (s) |
+---------------------+--------------------------------------+-------------+--------------+-------------+--------------+-------------+---------------+----------------+-------------+--------------+--------------+---------------+--------------+
| 2020-05-25 06:05:52 | 6ffdedc2-9e4d-11ea-b3f1-901b0e6098d7 | full_Monday | 107374182400 |       25600 | 107374182400 |       25600 |   14461960192 |           3448 | 26369589248 |         6287 |  66542632960 |         15865 |          150 |
+---------------------+--------------------------------------+-------------+--------------+-------------+--------------+-------------+---------------+----------------+-------------+--------------+--------------+---------------+--------------+
    INFO: Backy complete.

**Comment by wamdam** [comment]
What should change in your oppinion?

**Comment by noeyhuy** [comment]
After backup, I should check if the block data is normal. (data integrity and Reliability)

**Comment by wamdam** [comment]
If there's nothing to complain about after a scrub, backy2 just exits 0 and all is good.
If it finds any problems, it's
 - marking the backup invalid (column valid is 0)
 - marking the blocks invalid (internal detail, you won't notice but backy2 will not base new forward incremental backups on them)
 - CRY VERY LOUD AND CLEAR ABOUT IT

;)
So if you see nothing, all is good. It's meant for cron.
