### ISSUE TITLE
Could not locate column in row for column 'DISTINCT blocks.uid'

### ISSUE THREAD

**Issue by noeyhuy** [wamdam/backy2#84]
# please solve it. (DB : postgresql)
c:\Python38\Scripts>backy2 cleanup -f
    INFO: [backy2.logging] $ c:\Python38\Scripts\backy2 cleanup -f
   ERROR: [backy2.logging] "Could not locate column in row for column 'DISTINCT blocks.uid'"
   ERROR: [backy2.logging] Backy failed.

**Comment by wamdam** [comment]
Not enough information / works here.
