### ISSUE TITLE
An error is reported when backing up two volumes at the same time

### ISSUE THREAD

**Issue by feeyman** [wamdam/backy2#88]
![image](https://user-images.githubusercontent.com/24524775/129828723-b3a086df-0419-4fb6-9591-0492f54259bc.png)

### Hello, I'm very happy to use such a good tool. The version is 2.13.8. Excuse me, can't this backup software backup two volumes at the same time? Can it only run in a single thread? Looking forward to your reply, thank you.

**Comment by wamdam** [comment]
That should work. However there are currently 2 jobs during which backy2 requires exclusive access: rekey and full-cleanup. While one of these is running, no other backy2s can run.
