### ISSUE TITLE
Backup restore failed

### ISSUE THREAD

**Issue by ocelotsolutions** [wamdam/backy2#92]
For all backups in the list:

ERROR: [backy2.logging] Exception during reading from the data backend: [Errno File /mnt/backupstorage/nfs/backy-data/df/47/df4720e427DuHhPnFxiqjkYboBuwcx33.blob not found.] Block(uid='df4720e427DuHhPnFxiqjkYboBuwcx33', version_uid='d2c7daea-d33d-11ec-940c-96000054dad8', id=2269, date=datetime.datetime(2022, 5, 14, 4, 25, 34, 268365), checksum='3f9e81cb1c1e8a1fbe8b190665c0e454115a1775334f9d5160627959e0242ee36a7ec32af9425abb8e3ac691ee232586d766892e06e548bc59e0709177fa5948', size=4194304, valid=1, enc_envkey='...', enc_version=1, enc_nonce='b5a3cf9b3b9dbfdde1bfb014a54ac326')

**Comment by wamdam** [comment]
As the error says: blob not found. Maybe it's a bit unhappy to post the encryption key. I have tried to remove it.
You can try to check if there's a file /mnt/backupstorage/nfs/backy-data/df/47/df4720e427DuHhPnFxiqjkYboBuwcx33.blob on your server and if backy2 has access to it.

**Comment by wamdam** [comment]
As there has been no answer and this doesn't look like a software bug, I will now mark this ticket as closed.
