### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by bjornbouetsmith** [wamdam/backy2#96]
Hi,

Just a question - is this project dead - considering that no new code has been committed since Sep 26, 2021 - or is it simply because there are no new versions to keep up to date?

I get if software is stable, and it just works and it does not require updates - but with new versions of ceph etc, there might be issues coming up?

I would like to try this out, but if its no longer being maintained I dont want to use this for backing up my ceph block storage.

**Comment by wamdam** [comment]
Read the readme. https://github.com/wamdam/backy2
